import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

const contents = [
  "// Generated by scripts/sync-version.mjs during release. Do not edit by hand.",
  `export const VERSION = ${JSON.stringify(version)};`,
  "",
].join("\n");

writeFileSync(join(root, "src", "version.ts"), contents);

console.log(`src/version.ts synced to ${version}`);
